version: "3"

services:
  db:
    container_name: food_truck_finder_db
    image: postgis/postgis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    container_name: food_truck_finder_app
    build: .
    restart: on-failure
    command: >
      sh -c "chmod +x ./_scripts/init.sh && ./_scripts/init.sh"
    volumes:
      - .:/app
      - persistent_data:/persistent_data
    environment:
      - CSV_FILE_PATH=./_data/food-truck-data.csv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  persistent_data:
