version: "3"

services:
  app:
    container_name: food_truck_finder_app
    build: .
    command: >
      sh -c "chmod +x ./_scripts/init.sh && ./_scripts/init.sh"
    volumes:
      - .:/app
      - persistent_data:/persistent_data
    environment:
      - CSV_FILE_PATH=./_data/food-truck-data.csv
    ports:
      - "8000:8000"

  db:
    container_name: food_truck_finder_db
    image: postgis/postgis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  pgdata:
  persistent_data:
